### ISSUE TITLE
Alignment issues

### ISSUE THREAD

**Issue by tobiasbork** [corona-school/web-user-app#12]
The separation line between header and body is not aligned correctly. The menu bar seems to have a slightly lower separation line than the rest of the page.

**Comment by LeonErath** [comment]
Without a picture, I don't know what you mean. 😅

**Comment by tobiasbork** [comment]
![Capture](https://user-images.githubusercontent.com/39235832/85953037-dedfbc80-b96d-11ea-827e-6256b8c53290.PNG)
