### ISSUE TITLE
Crash on course detail page for pupils

### ISSUE THREAD

**Issue by geroembser** [corona-school/web-user-app#151]
There is error on the course detail page for pupils. Even though it is hidden in React's production build, it should be fixed, since it still is a bug (which primarily disturbs development): 
```
TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
```

Seems to have been introduced with #140, specifically this causes a problem: https://github.com/corona-school/web-user-app/blob/4e4379b7e7cfa32e3e667e9d8de3392fda9e0698/src/routes/CourseDetail.tsx#L141

**Comment by realmayus** [comment]
Seems like this was fixed in 5f40a81
