### ISSUE TITLE
Replace text

### ISSUE THREAD

**Issue by tobiasbork** [corona-school/web-user-app#17]
- [ ] The certificate explanation text currently states

```
Das Ausmaß und die genauen Inhalte der ehrenamtlichen Tätigkeit werden durch deine*n Schüler*in bestätigt. Um den Prozess so einfach wie möglich zu gestalten, kannst du auf der folgenden Seite
- das zeitliche Ausmaß der ehrenamtlichen Tätigkeit
- die genauen Inhalte und Aufgaben der ehrenamtlichen Tätigkeit angeben.
Daraus erstellen wir dir ein fertiges PDF, welches du an deine*n Schüler*in zum Unterschreiben schicken kannst.
```

The word "angeben" should be placed in the next line starting with 'Daraus erstellen wir dir ein fertiges PDF...'

-  [ ] The settings tab currently has a tag "Stundent\*in" which should be replaced by "Student\*in"

-  [ ] When submitting a course to review fails, the pop-up currently states "Kurs konnte zur Prüfung freigegeben werden". However, it should state "Kurs konnte nicht zur Prüfung freigegeben werden".

**Comment by morrme** [comment]
> * [ ]  The certificate explanation text currently states
> 
> ```
> Das Ausmaß und die genauen Inhalte der ehrenamtlichen Tätigkeit werden durch deine*n Schüler*in bestätigt. Um den Prozess so einfach wie möglich zu gestalten, kannst du auf der folgenden Seite
> - das zeitliche Ausmaß der ehrenamtlichen Tätigkeit
> - die genauen Inhalte und Aufgaben der ehrenamtlichen Tätigkeit angeben.
> Daraus erstellen wir dir ein fertiges PDF, welches du an deine*n Schüler*in zum Unterschreiben schicken kannst.
> ```
> 
> The word "angeben" should be placed in the next line starting with 'Daraus erstellen wir dir ein fertiges PDF...'
> 


Should "angeben" be placed at the end of that line @tobiasbork  ?

**Comment by tobiasbork** [comment]
The next sentence should state:
_angeben. Daraus erstellen wir dir ein fertiges PDF ..._
