### ISSUE TITLE
Certificate adjust workload

### ISSUE THREAD

**Issue by tobiasbork** [corona-school/web-user-app#18]
Currently, when generating the certificate PDF the entered hours for the weekly and total workload are rounded downwards. However, the PDF should state the same number of hours as the user entered even if that means displaying floats instead of integers. The step size should be 0.25 for both measures. The text-fields should be right-aligned.

**Comment by geroembser** [comment]
This looks like a primary backend problem. I think the frontend will only need to fix the problem that occurs if someone enters a number via his keyboard that could only have been created if the step size would be different than 0.25.

But I have another question @tobiasbork what do you mean with _"The text-fields should be right-aligned."_? Only the single textfield for the workload/"Zeit"? Or every textfield in the certificate progress (which I think is pretty ugly)? Or something else? I even think only making the workload textfield right-aligned wouldn't be such a good idea.

**Comment by tobiasbork** [comment]
Leave out the part with text alignments.
