### ISSUE TITLE
dashboard registration mobile optimization

### ISSUE THREAD

**Issue by tobiasbork** [corona-school/web-user-app#25]
Currently, the mobile registration version under IOS looks something like this.
![IMG-20200706-WA0000](https://user-images.githubusercontent.com/39235832/86584672-8c158e80-bf85-11ea-87e6-626db663573b.jpg)
It seems like there are some alignment issues as well as parts of the form not displaying correctly.

**Comment by LeonErath** [comment]
will be fixed within the next version. Also it affects only the registration of tutors and not tutees.
