### ISSUE TITLE
Error course creation

### ISSUE THREAD

**Issue by reinerschristopher** [corona-school/web-user-app#31]
When creating a course one receives an error message that the creation failed if the short description is longer than the accepted number of characters. This error message should be adjusted (e.g. "Die Kurzbeschreibung darf maximal 140 Zeichen lang sein").

**Comment by geroembser** [comment]
Implemented with https://github.com/corona-school/web-user-app/commit/fc154667cd2b8dbb2216c414ebcf06f23f70dd7b
