### ISSUE TITLE
Course edit information

### ISSUE THREAD

**Issue by tobiasbork** [corona-school/web-user-app#37]
Currently, there is no scroll bar when editing a course and hence, content is overflowing. 
Furthermore, when editing the course users receive "Ein Fehler ist aufgetreten" and hence, changes cannot be saved.

![image](https://user-images.githubusercontent.com/39235832/87477099-d8b53580-c627-11ea-890b-e8b3ba275a52.png)
![image](https://user-images.githubusercontent.com/39235832/87477292-2cc01a00-c628-11ea-90f6-731e4bc60f56.png)

**Comment by geroembser** [comment]
Should be fixed with 55a75958977efec9a20d0868e9c5e6b12ff5e1d7. Otherwise reopen that issue.
