### ISSUE TITLE
Create course

### ISSUE THREAD

**Issue by tobiasbork** [corona-school/web-user-app#40]
Currently, users seem to have trouble creating a course. I was able to recreate the scenario and couldn't continue to step 2 in the creation process because of an error that occurred. Furthermore, courses seem to display twice after filling in the information.

![image](https://user-images.githubusercontent.com/39235832/87478913-d6a0a600-c62a-11ea-89b3-02e8ed2087bd.png)

**Comment by geroembser** [comment]
Does this still happen? Haven't heard any more complaints about that. Otherwise @tobiasbork please provide more information to reproduce or close this.
