### ISSUE TITLE
Instructor settings tab misleading for Instructors

### ISSUE THREAD

**Issue by tobiasbork** [corona-school/web-user-app#54]
Currently, the settings tab for instructors has several options which are meant for a different case and hence might be misleading. This is an issue if the person is **only** registered as an instructor. If a person is registered for both (isStudent and isInstructor) nothing needs to happen.

The following items should be removed:
- certificate
- subjects
- tag "Student*in" (since instructors do not have to be students)
- word "Fächer" since there are none

![image](https://user-images.githubusercontent.com/39235832/88467332-5dc90600-ced6-11ea-97ad-30ec463ce556.png)

**Comment by LeonErath** [comment]
Should something else be displayed instead of a student? This also applies to the navigation bar. We could display something like "intern" and / or "tutor". @tobiasbork

**Comment by tobiasbork** [comment]
Tutor*in would work, yes.
Praktikant*in should be avoided since it is temporary.
