### ISSUE TITLE
Wrong number of participants displayed

### ISSUE THREAD

**Issue by tobiasbork** [corona-school/web-user-app#56]
Currently, for some courses there seems to be different participant numbers displayed.

**Example**:
In the course overview tab it says the course "Leichter lernen mit Sketchnoting" has 1/10 participants.
However, on the detailed view it says there are 11/10 participants (which is the correct number, since once person was added manuelly on top)

![image](https://user-images.githubusercontent.com/39235832/88479680-32373180-cf51-11ea-82ec-e7ff8d7c05ce.png)
![image](https://user-images.githubusercontent.com/39235832/88479690-3d8a5d00-cf51-11ea-8ca0-e8d6ab0e06a6.png)

**Comment by LeonErath** [comment]
I cannot re-enact the problem. In general, we actually show exactly what the API gives us. Does the problem occur with several courses? @tobiasbork

**Comment by tobiasbork** [comment]
I did not see this problem for several courses, only this one.
Even more interesting, in my personal user area everything works correctly even with this course, I was logged into someone elses. It seems like a minor bug which is not relevant for us.

**Comment by geroembser** [comment]
I took a look at this. Seems to be a general problem: all courses a participant has joined were shown to that participant with exactly 1 participant. But only in the list view under the "Meine Kurse" section. Looks like a problem with the API (so backend stuff). Thus I will close this here.
