### ISSUE TITLE
Improve error handling on public course page

### ISSUE THREAD

**Issue by geroembser** [corona-school/web-user-app#66]
For example if the client cannot reach the server, it will just show _"Es gibt im Moment keine Kurse"_. 
This is obviously not a correct error handling. But it looks like that it was somehow started to implement an error handling, but it is commented out:
https://github.com/corona-school/web-user-app/blob/0a36500fbd4ffade5957aded13dcaeb1b082837a/src/routes/PublicCourse.tsx#L60-L62
So this should be improved in the future.

**Comment by realmayus** [comment]
![Screenshot 2021-01-09 at 14 49 23](https://user-images.githubusercontent.com/38134006/104093282-defc3580-5289-11eb-9fd0-85c318aaac6c.png)

I think this was fixed by @LeonErath
