### ISSUE TITLE
Subjects lost on tutee's settings page

### ISSUE THREAD

**Issue by tobiasbork** [corona-school/web-user-app#68]
Currently, there is no option to neither see nor edit subjects in the settings tab. This should be added again to avoid confusion.
![image](https://user-images.githubusercontent.com/39235832/90543957-b2cf0380-e186-11ea-97c4-91bfd1d320a6.png)

**Comment by geroembser** [comment]
Only tutees/pupils are no longer able to see their selected subjects under the settings page. Therefore they're also not able to edit their subjects.

This seems to have began with 8a7afec. In previous commits the settings page looked like this:
![Bildschirmfoto 2020-08-28 um 22 24 24](https://user-images.githubusercontent.com/17550890/91617827-2ba13d00-e989-11ea-818a-2072d8ea4c65.png)

It now looks like this, which is wrong:
![Bildschirmfoto 2020-08-28 um 22 24 46](https://user-images.githubusercontent.com/17550890/91617819-26dc8900-e989-11ea-83f6-deb7b4a68086.png)
