### ISSUE TITLE
Cannot hide screening invitation pop-up

### ISSUE THREAD

**Issue by geroembser** [corona-school/web-user-app#73]
When a tutor/student opens the settings tab in the user area (user section / "Userbereich") she will see a popup with an invitation to a screening interview. But the later ("Später") button to hide that popup no longer works. The popup will hide but immediately re-appears. The later button should hide the screening popup as long as the user is on the selected tab (settings tab). 
Please see the following as an example of the bug: 
![Bildschirmvideo aufnehmen 2020-08-28 um 21 21 39](https://user-images.githubusercontent.com/17550890/91608363-b1b38880-e975-11ea-9099-70030f21a523.gif)

This is primarily strange due to the following fact: When a tutor/student registers for Corona School, she will get an email with the request to verify her email address. If she clicks on that link, her email address gets verified and she will get redirected to the settings tab of the user area ("Userbereich"). That user area then renders entirely unusable if the register and cannot immediately go to the screening.

**Comment by reinerschristopher** [comment]
We have gotten a couple of support mails regarding this issue, this should be fixed as soon as possible.

**Comment by geroembser** [comment]
@FunnyNameHaha is already working on that!
