### ISSUE TITLE
Dissolve Match Text Pupil

### ISSUE THREAD

**Issue by reinerschristopher** [corona-school/web-user-app#76]
Currently, when dissolving a match as a pupil the text displayed is written for students. The questions should state: "Konnte _name pupil_ dich erfolgreich unterstützen?" and "Warum konnte _name pupil_ dich nicht unterstützen?"
<img width="646" alt="Bildschirmfoto 2020-09-01 um 18 12 51" src="https://user-images.githubusercontent.com/38394210/91878171-33116080-ec7f-11ea-8543-5124a2642fde.png">

**Comment by geroembser** [comment]
I think you mean the following
* "Konnte _name **student**_ dich erfolgreich unterstützen?"
* "Warum konnte _name **student**_ dich nicht unterstützen?"
