### ISSUE TITLE
Dissolve Match Pupil Text

### ISSUE THREAD

**Issue by tobiasbork** [corona-school/web-user-app#78]
Currently, the text for dissolving a match from a pupil perspective is misleading since it is written for students.

**Instead of**
_Konntest du [Name Student] erfolgreich unterstützen?
Wir möchten uns bei dir für deine Hilfe bedanken!_

_Ohne dich wäre dieses Projekt nicht möglich. Danke, dass du in dieser schwierigen Zeit gesellschaftliche Verantwortung übernommen hast!_

_Sobald du die Zusammenarbeit endgültig beendest, werden wir [Name Student] darüber per E-Mail informieren. [Name Student] hat dann die Möglichkeit sich bei Bedarf neu verbinden zu lassen._

**it should state**
_Konnte dich [Name Student] erfolgreich unterstützen?_

In case the answer is "yes":
_Vielen Dank für deine Rückmeldung!_
_Sobald du die Zusammenarbeit endgültig beendest, werden wir [Name Student] darüber per E-Mail informieren. [Name Student] hat dann die Möglichkeit sich bei Bedarf neu verbinden zu lassen._

In case the answer is "no", the text is already correct.

**Comment by geroembser** [comment]
I think this is partly a duplicate of https://github.com/corona-school/web-user-app/issues/76. 

I guess the only thing that's still "wrong" or misleading is the part _"Ohne dich wäre dieses Projekt nicht möglich. [...]"_. 
So here we only need to do the _"Vielen Dank für deine Rückmeldung!"_ part. 

@FunnyNameHaha you've fixed #76, so could you take a look at this as well?
