### ISSUE TITLE
Save function for subjects not working

### ISSUE THREAD

**Issue by tobiasbork** [corona-school/web-user-app#81]
Currently, it seems like the **save** option for adding new subjects is not working. When clicking the button nothing happens. This should be fixed.
![image](https://user-images.githubusercontent.com/39235832/93756688-c21df280-fc05-11ea-9f2e-f2ab4a2e424b.png)

**Comment by geroembser** [comment]
Can you provide more information on how to reproduce it? Sounds pretty stupid, but I can't reproduce it that easily. 

So there is basically an error if someone has no internet connection (which isn't handled appropriately by the frontend), but this error shouldn't occur that frequent.

**Comment by geroembser** [comment]
Ok, just another idea: it seems to be backend related where wrong subject parsing will lead to some problems. This only happens for some special subject formats used for some tutees (related to support of legacy subject format). I think I’ll need to look into this again later today. But @tobiasbork I’m pretty sure that you can name me a special user for which the problem occurs and which has this unusual/wrongly handled subject format in the database.
