### ISSUE TITLE
Screening popup for coaches does not disappear

### ISSUE THREAD

**Issue by geroembser** [corona-school/web-user-app#92]
Even if a project coach was successfully screened, the screening popup (e.g. visible under settings) will not disappear. The problem only exists if someone is only participating as a project coach (i.e. not as a tutor or instructor too) or if someone only got

**Comment by geroembser** [comment]
The backend API already provides the `projectCoachingScreeningStatus`. I think the frontend only needs to use it when deciding whether to show the popup or not.

**Comment by lsc0498** [comment]
Should be fixed in `1de00309`
