### ISSUE TITLE
Adjust open match request limit for students

### ISSUE THREAD

**Issue by geroembser** [corona-school/web-user-app#93]
As a student/tutor you should only be able to have at most three open match requests at the same time. This limit is enforced in the backed, but not yet here in the frontend. So for example assume a student that has one active match: he goes to the matching tab and requests three more matches. The student then sees three cards, one for every open match request. But at the same time the person still sees the card that allows him to request even another match. When he clicks on that button/card, an error will occur (because the backend correctly enforces the limit). So we should just hide this in case of three open match requests.

Please see https://github.com/corona-school/project-user/issues/22 for infos on the limit.

<img width="1732" alt="Bildschirmfoto 2020-11-18 um 23 45 41" src="https://user-images.githubusercontent.com/17550890/99597395-369fc280-29f8-11eb-88a3-e7967493ff64.png">

**Comment by lsc0498** [comment]
Solved in commit [`111e34fa`](https://github.com/corona-school/web-user-app/commit/111e34fade1bfb1c00482f1cb2c32ab48d53c840)
